export class Leave {
    constructor(
        public Key?: string,
        public Employee_No?: string,
        public Employee_Name?: string,
        public _x003C_Global_Dimension_1_Code_x003E_?: string,
        public Global_Dimension_2_Code?: string,
        public Application_No?: string,
        public Application_Date?: string,
        public User_ID?: string,
        public Leave_Code?: string,
        public Leave_Type_Decription?: string,
        public Start_Date?: string,
        public Days_To_Go_on_Leave?: string,
        public End_Date?: string,
        public Total_No_Of_Days?: string,
        public Leave_balance?: string,
        public Half_Day_on_Start_Date?: string,
        public Half_Day_on_End_Date?: string,
        public Holidays?: string,
        public Weekend_Days?: string,
        public Days?: string,
        public Balance_After?: string,
        public Return_Date?: string,
        public Reporting_Date?: string,
        public Comments?: string,
        public Reliever?: string,
        public Reliever_Name?: string,
        public Appointment_Date?: string,
        public Phone_No?: string,
        public E_Mail_Address?: string,
        public Grade?: string,
        public Status?: string,
        public Approval_Entries?: string,
        public Leave_Allowance?: string,
        public Rejection_Comments?: string,
        public Days_Applied?: string,
        

    ) {}
}